version: '3'
services:
  motion:
    image: tuxthepenguin/motion:ubuntu-latest
    container_name: motion
    networks:
      - haproxy
    volumes:
      - ./data/config:/etc/motion
      - ./data/config/conf.d:/etc/motion/conf.d
      - /etc/localtime:/etc/localtime:ro
    #ports:
    #  - '8080:8080'
    #  - '80:80'
    restart: unless-stopped

networks:
  haproxy:
    external: true